default: &default
  adapter: redis
  url: redis://localhost:6379/1

development:
  <<: *default
  channel_prefix: bdgtshr_development

test:
  <<: *default
  channel_prefix: bdgtshr_test

production:
  <<: *default
  channel_prefix: bdgtshr_production
